### ISSUE TITLE
ERROR: Cannot parse privateKey: Encrypted OpenSSH private key detected, but no passphrase given

### ISSUE THREAD

**Issue by moalamri** [liying2008/easy-deployment#1]
Hi.

I have server that is only accessible with authorized key. The key has a **passphrase**.

When I run deploy I get the following. 

```
Start deployment...
Establish ssh connection.

ERROR: Cannot parse privateKey: Encrypted OpenSSH private key detected, but no passphrase given

Deployment failed!
```

I tried to add the passphrase to the settings, but it doesn't work and there's no such key in documents.
What should I do?

**Comment by liying2008** [comment]
Sorry for the late reply. This problem has been fixed in version 0.0.5, please try again after updating to version 0.0.5, thanks!
